### ISSUE TITLE
svm情感识别代码结果都是100%这不合理吧，请问这是为什么呀

### ISSUE THREAD

**Issue by jwcen** [busyyang/python_sound_open#2]
![image](https://user-images.githubusercontent.com/45908358/109772490-01cb1a80-7c39-11eb-9aa4-4d1034835d99.png)

**Comment by busyyang** [comment]
首先，这个结果在我这个环境中并不是100%，
![image](https://user-images.githubusercontent.com/7272659/109779245-b7e63280-7c40-11eb-9bd6-c7e4a3565d70.png)

其次，这个结果的确不是准确的，因为我们使用了训练集的一部分数据来进行测试的，一般来说要求测试集是不包含于训练集的，用测试集的结果来评价模型的拟合能力，这里只是简单演示了SVM的使用。如果需要真实评价模型，需要将数据切分一部分来训练，剩下的一部分来测试。比如我这里简单取80%做训练，另外20%做测试的话：
~~~py
......
data = np.hstack((fear, happy, neutral, sadness, anger)).T
y = np.array([[i] * 50 for i in range(5)]).flatten()
clf = svm.SVC()
train = [True if (i + 1) % 5 != 0 else False for i in range(250)]
test = [True if (i + 1) % 5 == 0 else False for i in range(250)]
clf.fit(data[train], y[train])
yp = clf.predict(data[test])
confusion_matrix_info(y[test], yp)
print(classification_report(y[test], yp, target_names=['fear', 'happy', 'neutr', 'sad', 'anger']))
~~~

![image](https://user-images.githubusercontent.com/7272659/109780720-398a9000-7c42-11eb-8f32-e16fbdc0231e.png)

**Comment by jwcen** [comment]
原来如此，谢谢大佬！
还想请问下，您用的mat格式的文件是已经做好特征工程了吧，直接用没问题吧?
我用的casia数据集，准确率不高









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "busyyang/python_sound_open"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午5:03
收件人:&nbsp;"busyyang/python_sound_open"<python_sound_open@noreply.github.com&gt;;
抄送:&nbsp;"大屁孩不放屁"<1823045248@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [busyyang/python_sound_open] svm情感识别代码结果都是100%这不合理吧，请问这是为什么呀 (#2)





 
首先，这个结果在我这个环境中并不是100%，
 
 
其次，这个结果的确不是准确的，因为我们使用了训练集的一部分数据来进行测试的，一般来说要求测试集是不包含于训练集的，用测试集的结果来评价模型的拟合能力，这里只是简单演示了SVM的使用。如果需要真实评价模型，需要将数据切分一部分来训练，剩下的一部分来测试。比如我这里简单取80%做训练，另外20%做测试的话：
 ...... data = np.hstack((fear, happy, neutral, sadness, anger)).T y = np.array([[i] * 50 for i in range(5)]).flatten() clf = svm.SVC() train = [True if (i + 1) % 5 != 0 else False for i in range(250)] test = [True if (i + 1) % 5 == 0 else False for i in range(250)] clf.fit(data[train], y[train]) yp = clf.predict(data[test]) confusion_matrix_info(y[test], yp) print(classification_report(y[test], yp, target_names=['fear', 'happy', 'neutr', 'sad', 'anger']))

**Comment by busyyang** [comment]
mat文件已经提了特征，你使用其他数据集应该也要先提取特征再用SVM分类

**Comment by jwcen** [comment]
ok，感谢！







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "busyyang/python_sound_open"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午5:25
收件人:&nbsp;"busyyang/python_sound_open"<python_sound_open@noreply.github.com&gt;;
抄送:&nbsp;"大屁孩不放屁"<1823045248@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [busyyang/python_sound_open] svm情感识别代码结果都是100%这不合理吧，请问这是为什么呀 (#2)





 
mat文件已经提了特征，你使用其他数据集应该也要先提取特征再用SVM分类

**Comment by jwcen** [comment]
作者您好，
&nbsp; &nbsp; &nbsp; 是这样的，我这几天看了挺多篇文献，发现他们中文语音情感识别的识别率基本都在80~90%。我用您的代码跑出来的结果都普遍偏高基本在90%以上，数据库用的是CASIA，没有用您的数据集。
&nbsp; &nbsp; &nbsp; 所以我就比较疑惑这个识别率的准确性是不是正确的，不知道您有什么见解吗
&nbsp; &nbsp; &nbsp; 叨扰了。




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "busyyang/python_sound_open"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 上午10:12
收件人:&nbsp;"busyyang/python_sound_open"<python_sound_open@noreply.github.com&gt;;
抄送:&nbsp;"大屁孩不放屁"<1823045248@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [busyyang/python_sound_open] svm情感识别代码结果都是100%这不合理吧，请问这是为什么呀 (#2)





 
Closed #2.

**Comment by busyyang** [comment]
识别的准确性与很多因素相关，比如特征工程，数据集大小，分类数量，分类器，分类器参数等。代码应该是没什么问题的，因为这里真正的SVM代码只有一行`clf.fit(data[train], y[train])`, 如果是怀疑准确性过高的问题，那么看下用于测试的数据是否参与了训练，一般不允许是参与训练的数据做测试。
另外，看下其他论文测试集训练集的划分，按照他们的方式划分试试看。我不清楚这个CASIA数据集，没用过，通常特征做得好的话，90%多一些，不是0.99这种夸张的情况，一般都没什么问题。
