### ISSUE TITLE
SPL函数出错

### ISSUE THREAD

**Issue by leileilin** [busyyang/python_sound_open#3]
`for i in range(length // M - 1):
            s = data[i * M:(i + 1) * M]
            spls[i] = spl_cal(s, fs, frameLen)`
这里面的length 应该改成 len(data)吧？

**Comment by busyyang** [comment]
前面有定义length 就是len(data)，178行
~~~python
length = len(data)
~~~

**Comment by leileilin** [comment]
> 前面有定义length 就是len(data)，178行
> 
> ```python
> length = len(data)
> ```

但是对最后一帧是有额外的操作阿，那时候的len(data)和之前不一样了。

**Comment by busyyang** [comment]
好像是有点问题，改成len(data)吧。
